spring:
  datasource:
    url: jdbc:mysql://localhost:3306/videojuegos
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  thymeleaf:
    cache: false
  mvc:
    format:
      date: dd-MM-yyyy
  mail:
    host: smtp.gmail.com
    port: 587
    username: grupo6.egg@gmail.com
    password: 123grupo6.egg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
          ssl:
            trust: smtp.gmail.com
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org:
      springframework:
        web: debug
custom:
  upload-path: src/main/resources/static/uploads
  nombre-sistema: Sistema Gestión Videojuegos

#server:
#    error:
#        path: /error
#        whitelabel:
#            enabled: false